"""
Placement Aptitude Skill Schema

Defines the structured output for aptitude test questions.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class AptitudeQuestionContent(BaseModel):
    """
    Content generated by LLM for aptitude questions.
    Does NOT include database identifiers.
    """
    question_type: str = Field(..., description="Type: quantitative, logical, verbal")
    topic: str = Field(..., description="Specific topic within aptitude")
    difficulty: str = Field(..., description="Difficulty level: easy, medium, hard")
    question: str = Field(..., description="The aptitude question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer")
    explanation: Optional[str] = Field(default=None, description="Explanation of the answer")


class AptitudeQuestion(BaseModel):
    """
    Internal question model with backend-generated identifiers.
    """
    question_id: str = Field(..., description="Unique identifier (generated by backend)")
    question_type: str = Field(..., description="Type: quantitative, logical, verbal")
    topic: str = Field(..., description="Specific topic")
    difficulty: str = Field(..., description="Difficulty level")
    question: str = Field(..., description="The aptitude question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer")
    explanation: Optional[str] = Field(default=None, description="Explanation")


class AptitudeOutput(BaseModel):
    """Aptitude skill output schema."""
    
    status: str = Field(description="Status: in_progress, completed")
    
    question_content: Optional[AptitudeQuestionContent] = Field(
        default=None,
        description="Aptitude question content (LLM generated, no IDs)"
    )
    
    question: Optional[AptitudeQuestion] = Field(
        default=None,
        description="Aptitude question with backend-generated question_id"
    )
    
    score: Optional[float] = Field(default=None, description="Score if completed")
    
    strengths: List[str] = Field(
        default_factory=list,
        description="Identified strengths"
    )
    
    weaknesses: List[str] = Field(
        default_factory=list,
        description="Identified weaknesses"
    )
    
    next_action: str = Field(description="Next action: placement_coding or continue")
