"""
Survey Skill Output Schema

Defines the structured output expected from the LLM.
Separates LLM content generation from backend identifier generation.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field, field_validator, model_validator
from core.skill_output import UniversalSkillOutput


# ---------------------------------------------------
# LLM Output Schema - Content Only
# ---------------------------------------------------

class SurveyQuestionContent(BaseModel):
    """
    Content generated by LLM for Survey questions.
    Does NOT include database identifiers or metadata.
    """
    question: str = Field(
        description="The survey question"
    )
    
    options: List[str] = Field(
        description="List of 4 answer options for the MCQ"
    )
    
    explanation: Optional[str] = Field(
        default=None,
        description="Explanation of the question context (not a correct answer)"
    )
    
    @field_validator('question')
    @classmethod
    def question_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError('question must not be empty')
        return v.strip()
    
    @field_validator('options')
    @classmethod
    def options_must_have_exactly_four(cls, v: List[str]) -> List[str]:
        if len(v) != 4:
            raise ValueError(f'options must have exactly 4 items, got {len(v)}')
        for i, opt in enumerate(v):
            if not opt or not opt.strip():
                raise ValueError(f'option[{i}] must not be empty')
        return [opt.strip() for opt in v]
    
    @field_validator('options')
    @classmethod
    def options_must_be_unique(cls, v: List[str]) -> List[str]:
        normalized = [opt.strip().lower() for opt in v]
        if len(set(normalized)) != len(normalized):
            raise ValueError('options must be unique')
        return v


# ---------------------------------------------------
# Internal Question Model - With Backend IDs
# ---------------------------------------------------

class MCQQuestion(BaseModel):
    """
    Internal question model with backend-generated identifiers.
    Used after LLM content validation and ID generation.
    """
    question_id: str = Field(
        description="Unique identifier for this question (generated by backend)"
    )
    
    question: str = Field(
        description="The survey question"
    )
    
    options: List[str] = Field(
        description="List of 4 answer options for the MCQ"
    )
    
    explanation: Optional[str] = Field(
        default=None,
        description="Explanation of the question context"
    )
    
    @field_validator('question_id')
    @classmethod
    def question_id_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError('question_id must not be empty')
        return v.strip()
    
    @field_validator('question')
    @classmethod
    def question_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError('question must not be empty')
        return v.strip()
    
    @field_validator('options')
    @classmethod
    def options_must_have_exactly_four(cls, v: List[str]) -> List[str]:
        if len(v) != 4:
            raise ValueError(f'options must have exactly 4 items, got {len(v)}')
        for i, opt in enumerate(v):
            if not opt or not opt.strip():
                raise ValueError(f'option[{i}] must not be empty')
        return [opt.strip() for opt in v]


# ---------------------------------------------------
# Student Profile
# ---------------------------------------------------

class StudentProfile(BaseModel):

    career_goal: Optional[str] = Field(
        default=None,
        description="Target career role"
    )

    target_company: Optional[str] = Field(
        default=None,
        description="Dream company"
    )

    experience_level: Optional[str] = Field(
        default=None,
        description="Current experience level"
    )

    primary_language: Optional[str] = Field(
        default=None,
        description="Preferred programming language"
    )

    known_skills: List[str] = Field(
        default_factory=list,
        description="Skills student already knows"
    )

    projects: Optional[int] = Field(
        default=0,
        description="Number of completed projects"
    )

    study_hours: Optional[int] = Field(
        default=1,
        description="Daily study hours"
    )

    learning_style: Optional[str] = Field(
        default=None,
        description="Preferred learning style"
    )

    weak_topics: List[str] = Field(
        default_factory=list,
        description="Weak concepts"
    )

    timeline: Optional[str] = Field(
        default=None,
        description="Target interview timeline"
    )


# ---------------------------------------------------
# Survey Output
# ---------------------------------------------------

class SurveyOutput(BaseModel):

    question_type: Literal["mcq", "completed"] = Field(
        default="completed",
        description="Type of question: 'mcq' for multiple choice, 'completed' when survey is done"
    )

    status: str

    survey_completed: bool

    profile: StudentProfile

    confidence: float = Field(
        ge=0,
        le=1,
        description="How confident the AI is about the collected profile"
    )

    missing_information: List[str] = Field(
        default_factory=list,
        description="Fields still missing"
    )

    mcq_question_content: Optional[SurveyQuestionContent] = Field(
        default=None,
        description="MCQ question content when question_type is 'mcq' (LLM generated, no IDs)"
    )

    mcq_question: Optional[MCQQuestion] = Field(
        default=None,
        description="MCQ question with backend-generated question_id (populated after validation)"
    )

    coach_notification: Optional[str] = Field(
        default=None,
        description="Completion notification for the Career Coach; never a workflow instruction."
    )
    
    @model_validator(mode='after')
    def validate_question_type_consistency(self) -> 'SurveyOutput':
        if self.question_type == "mcq":
            if self.mcq_question_content is None and self.mcq_question is None:
                raise ValueError("question_type is 'mcq' but both mcq_question_content and mcq_question are None")
        elif self.question_type == "completed":
            if self.mcq_question_content is not None or self.mcq_question is not None:
                raise ValueError("question_type is 'completed' but mcq fields are not None")
        return self
