"""
Placement Technical Skill Schema

Defines the structured output for technical interview questions.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class TechnicalQuestionContent(BaseModel):
    """
    Content generated by LLM for technical questions.
    Does NOT include database identifiers.
    """
    topic: str = Field(..., description="Technical topic: databases, system design, frameworks, etc.")
    difficulty: str = Field(..., description="Difficulty level: easy, medium, hard")
    question: str = Field(..., description="The technical question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options if applicable")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer for MCQ")
    explanation: Optional[str] = Field(default=None, description="Explanation of the answer")


class TechnicalQuestion(BaseModel):
    """
    Internal question model with backend-generated identifiers.
    """
    question_id: str = Field(..., description="Unique identifier (generated by backend)")
    topic: str = Field(..., description="Technical topic")
    difficulty: str = Field(..., description="Difficulty level")
    question: str = Field(..., description="The technical question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer")
    explanation: Optional[str] = Field(default=None, description="Explanation")


class TechnicalOutput(BaseModel):
    """Technical skill output schema."""
    
    status: str = Field(description="Status: in_progress, completed")
    
    question_content: Optional[TechnicalQuestionContent] = Field(
        default=None,
        description="Technical question content (LLM generated, no IDs)"
    )
    
    question: Optional[TechnicalQuestion] = Field(
        default=None,
        description="Technical question with backend-generated question_id"
    )
    
    score: Optional[float] = Field(default=None, description="Score if completed")
    
    strengths: List[str] = Field(
        default_factory=list,
        description="Identified strengths"
    )
    
    weaknesses: List[str] = Field(
        default_factory=list,
        description="Identified weaknesses"
    )
    
    next_action: str = Field(description="Next action: placement_interview or continue")
