"""
Placement Coding Skill Schema

Defines the structured output for coding interview questions.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class CodingQuestionContent(BaseModel):
    """
    Content generated by LLM for coding questions.
    Does NOT include database identifiers.
    """
    topic: str = Field(..., description="DSA topic: arrays, linked lists, trees, graphs, dynamic programming, etc.")
    difficulty: str = Field(..., description="Difficulty level: easy, medium, hard")
    question: str = Field(..., description="The coding problem statement")
    constraints: List[str] = Field(
        default_factory=list,
        description="Problem constraints"
    )
    examples: List[str] = Field(
        default_factory=list,
        description="Input/output examples"
    )
    hints: List[str] = Field(
        default_factory=list,
        description="Hints for solving the problem"
    )
    time_complexity: Optional[str] = Field(default=None, description="Expected time complexity")
    space_complexity: Optional[str] = Field(default=None, description="Expected space complexity")


class CodingQuestion(BaseModel):
    """
    Internal question model with backend-generated identifiers.
    """
    question_id: str = Field(..., description="Unique identifier (generated by backend)")
    topic: str = Field(..., description="DSA topic")
    difficulty: str = Field(..., description="Difficulty level")
    question: str = Field(..., description="The coding problem statement")
    constraints: List[str] = Field(default_factory=list, description="Problem constraints")
    examples: List[str] = Field(default_factory=list, description="Input/output examples")
    hints: List[str] = Field(default_factory=list, description="Hints for solving")
    time_complexity: Optional[str] = Field(default=None, description="Expected time complexity")
    space_complexity: Optional[str] = Field(default=None, description="Expected space complexity")


class CodingOutput(BaseModel):
    """Coding skill output schema."""
    
    status: str = Field(description="Status: in_progress, completed")
    
    question_content: Optional[CodingQuestionContent] = Field(
        default=None,
        description="Coding question content (LLM generated, no IDs)"
    )
    
    question: Optional[CodingQuestion] = Field(
        default=None,
        description="Coding question with backend-generated question_id"
    )
    
    score: Optional[float] = Field(default=None, description="Score if completed")
    
    code_quality: Optional[str] = Field(default=None, description="Code quality assessment")
    
    strengths: List[str] = Field(
        default_factory=list,
        description="Identified strengths"
    )
    
    weaknesses: List[str] = Field(
        default_factory=list,
        description="Identified weaknesses"
    )
    
    next_action: str = Field(description="Next action: placement_technical or continue")
