from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List


# ---------------------------------------------------
# LLM Output Schema - Content Only
# ---------------------------------------------------

class AssessmentQuestionContent(BaseModel):
    """
    Content generated by LLM for Assessment questions.
    Does NOT include database identifiers or metadata.
    """
    question: str = Field(..., description="The assessment question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options if applicable")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer for MCQ")
    explanation: Optional[str] = Field(default=None, description="Explanation of the answer")


# ---------------------------------------------------
# Internal Question Model - With Backend IDs
# ---------------------------------------------------

class AssessmentQuestion(BaseModel):
    """
    Internal question model with backend-generated identifiers.
    Used after LLM content validation and ID generation.
    """
    question_id: str = Field(..., description="Unique identifier for this question (generated by backend)")
    question: str = Field(..., description="The assessment question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options if applicable")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer for MCQ")
    explanation: Optional[str] = Field(default=None, description="Explanation of the answer")


class AssessmentOutputSchema(BaseModel):
    """
    Structured output expected from the LLM for the Assessment Skill.
    """
    next_question_content: Optional[AssessmentQuestionContent] = Field(
        default=None,
        description="The next adaptive question content (LLM generated, no IDs)"
    )
    next_question: Optional[AssessmentQuestion] = Field(
        default=None,
        description="The next adaptive question with backend-generated question_id"
    )
    difficulty: Optional[str] = Field(default="medium", description="The difficulty level of the new question (easy, medium, hard).")
    feedback: Optional[str] = Field(default="", description="Feedback on the user's previous answer.")
    topic_evaluations: Optional[Dict[str, Dict[str, str]]] = Field(
        default_factory=dict,
        description="Topic mastery levels. Example: {'Python': {'Decorators': 'mastered'}}."
    )
    is_complete: bool = Field(False, description="True if the assessment module is finished.")
