"""
Placement Skill Output Schema

Defines the structured output expected from the LLM for placement preparation.
The LLM generates placement questions, NOT placement profile scores.
Profile scores are calculated by the Evaluation Engine.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------
# LLM Output Schema - Content Only
# ---------------------------------------------------

class PlacementQuestionContent(BaseModel):
    """
    Content generated by LLM for Placement questions.
    Does NOT include database identifiers or profile scores.
    """
    question_type: str = Field(..., description="Type of placement question: aptitude, coding, technical, interview, hr")
    skill: str = Field(..., description="Skill area being tested")
    topic: str = Field(..., description="Specific topic within the skill")
    difficulty: str = Field(..., description="Difficulty level: easy, medium, hard")
    question: str = Field(..., description="The placement question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options if applicable")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer for MCQ")
    explanation: Optional[str] = Field(default=None, description="Explanation of the answer")


# ---------------------------------------------------
# Internal Question Model - With Backend IDs
# ---------------------------------------------------

class PlacementQuestion(BaseModel):
    """
    Internal question model with backend-generated identifiers.
    Used after LLM content validation and ID generation.
    """
    question_id: str = Field(..., description="Unique identifier for this question (generated by backend)")
    question_type: str = Field(..., description="Type of placement question")
    skill: str = Field(..., description="Skill area being tested")
    topic: str = Field(..., description="Specific topic within the skill")
    difficulty: str = Field(..., description="Difficulty level")
    question: str = Field(..., description="The placement question")
    options: Optional[List[str]] = Field(default=None, description="MCQ options if applicable")
    correct_option_index: Optional[int] = Field(default=None, description="Index of correct answer for MCQ")
    explanation: Optional[str] = Field(default=None, description="Explanation of the answer")


class PlacementOutput(BaseModel):
    """Placement skill output schema."""
    
    status: str = Field(description="Current placement status: in_progress, ready, needs_work")

    profile: Optional[dict] = Field(
        default=None,
        description="Student placement profile scores (e.g. technical_readiness, communication_score, etc.)"
    )
    
    # LLM generates question content
    question_content: Optional[PlacementQuestionContent] = Field(
        default=None,
        description="Placement question content (LLM generated, no IDs)"
    )
    
    # Backend adds question with ID
    question: Optional[PlacementQuestion] = Field(
        default=None,
        description="Placement question with backend-generated question_id"
    )
    
    recommendations: List[str] = Field(
        default_factory=list,
        description="Actionable recommendations for improvement"
    )
    
    next_steps: List[str] = Field(
        default_factory=list,
        description="Immediate next steps to take"
    )
    
    estimated_timeline: str = Field(
        description="Estimated timeline to reach placement readiness"
    )
    
    confidence: float = Field(
        ge=0,
        le=1,
        description="Confidence in the assessment"
    )
