"""
Placement Interview Skill Schema

Defines the structured output for behavioral interview questions.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class InterviewQuestionContent(BaseModel):
    """
    Content generated by LLM for interview questions.
    Does NOT include database identifiers.
    """
    category: str = Field(..., description="Category: behavioral, situational, leadership, teamwork")
    topic: str = Field(..., description="Specific topic within the category")
    difficulty: str = Field(..., description="Difficulty level: easy, medium, hard")
    question: str = Field(..., description="The interview question")
    evaluation_criteria: List[str] = Field(
        default_factory=list,
        description="Criteria for evaluating the answer"
    )
    sample_answer: Optional[str] = Field(default=None, description="Sample good answer")


class InterviewQuestion(BaseModel):
    """
    Internal question model with backend-generated identifiers.
    """
    question_id: str = Field(..., description="Unique identifier (generated by backend)")
    category: str = Field(..., description="Category")
    topic: str = Field(..., description="Specific topic")
    difficulty: str = Field(..., description="Difficulty level")
    question: str = Field(..., description="The interview question")
    evaluation_criteria: List[str] = Field(default_factory=list, description="Evaluation criteria")
    sample_answer: Optional[str] = Field(default=None, description="Sample good answer")


class InterviewOutput(BaseModel):
    """Interview skill output schema."""
    
    status: str = Field(description="Status: in_progress, completed")
    
    question_content: Optional[InterviewQuestionContent] = Field(
        default=None,
        description="Interview question content (LLM generated, no IDs)"
    )
    
    question: Optional[InterviewQuestion] = Field(
        default=None,
        description="Interview question with backend-generated question_id"
    )
    
    score: Optional[float] = Field(default=None, description="Score if completed")
    
    communication_score: Optional[float] = Field(default=None, description="Communication score")
    
    strengths: List[str] = Field(
        default_factory=list,
        description="Identified strengths"
    )
    
    weaknesses: List[str] = Field(
        default_factory=list,
        description="Identified weaknesses"
    )
    
    next_action: str = Field(description="Next action: placement_hr or continue")
